Payfinecontrol dipanshu
dharam4/jattcode pull request #18
Opened 2020-08-25 16:12 UTC by dipanshu42

Hey @akay08923 as my mediator can you please tell @dharam4  to review my payfinecontrol class as i have corrected the code according to the style guideline. so please ask him to give his feedback.

2020-08-27 07:03 UTC, dharam4 commented on library/Main.java
> +		  sb.append("  M  : add member\n")
If you wanna pout sb.append then there would be semicolon in the end of each line.

2020-08-27 07:27 UTC, dharam4 commented on library/Main.java
> +			lib = Library.GeTiNsTaNcE();                 //LIB = Library.GeTiNsTaNcE();
GeTiNsTaNcE should be getInstace

2020-08-27 07:27 UTC, dharam4 commented on library/Main.java
> +			CAL = Calendar.gEtInStAnCe();                //CAL = Calendar.gEtInStAnCe();
GeTiNsTaNcE should be corrected

2020-08-27 07:28 UTC, dharam4 commented on library/Main.java
> +			cal = Calendar.gEtInStAnCe();                //CAL = Calendar.gEtInStAnCe();
here also

2020-08-27 07:42 UTC, dharam4 requested changes
hi dipanshu , there are some errors which i mentioned in the comments please correct these as soon as possible

2020-08-27 07:51 UTC, dipanshu42 commented
Sure i will check and let you know

On Thu, 27 Aug, 2020, 5:42 pm dharam4, <notifications@github.com> wrote:

> *@dharam4* requested changes on this pull request.
>
> hi dipanshu , there are some errors which i mentioned in the comments
> please correct these as soon as possible
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dharam4/jattcode/pull/18#pullrequestreview-476464418>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQK62VIEBSITD3LWXRYKCY3SCYE6RANCNFSM4QK2TOSA>
> .
>

2020-08-27 13:58 UTC, dipanshu42 commented
Hey @navjeevan24  i have uploaded the code as per the suggested work, so now please ask the reviewer @dharam4  to go through it again and provide me his feedback.

2020-08-28 05:41 UTC, dharam4 approved these changes
yes all good @navjeevan24  , you can send the merge approval to dipanshu.

2020-08-28 05:54 UTC, merged