Merge pull request #4 from dharam4/Book_Navjeevan24
dharam4/jattcode pull request #9
Opened 2020-08-18 13:15 UTC by navjeevan24

hi, @dipanshu42 I have updated the code in ReturnBook class, so can you please send request to my Reviewer @akay08923 for review. Thanks

2020-08-18 13:17 UTC, dipanshu42 commented
> hi, @dipanshu42 I have updated the code in ReturnBook class, so can you please send request to my Reviewer @akay08923 for review. Thanks

no worries i,ll let ankush know about this and the work will be delivered asap

2020-08-18 13:18 UTC, dipanshu42 commented
No worries i'll let ankush know about this and the review will be delivered
asap

On Tue, 18 Aug, 2020, 11:15 pm navjeevan24, <notifications@github.com>
wrote:

> hi, @dipanshu42 <https://github.com/dipanshu42> I have updated the code
> in ReturnBook class, so can you please send request to my Reviewer
> @akay08923 <https://github.com/akay08923> for review. Thanks
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/dharam4/jattcode/pull/9
> Commit Summary
>
>    - Merge pull request #4 from dharam4/Book_Ankush
>
> File Changes
>
>    - *M* library/returnBook/ReturnBookUI.java
>    <https://github.com/dharam4/jattcode/pull/9/files#diff-01143b4ac46704ab1f3959225a223d42>
>    (44)
>
> Patch Links:
>
>    - https://github.com/dharam4/jattcode/pull/9.patch
>    - https://github.com/dharam4/jattcode/pull/9.diff
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dharam4/jattcode/pull/9>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQK62VMI6VBZJND4FHXRVQ3SBJ5G3ANCNFSM4QDON3SQ>
> .
>

2020-08-19 08:40 UTC, akay08923 requested changes
Hi @dipanshu42, i have reviewed the code which has been updated by @navjeevan24 . there was a one error on which i gave suggestion. Please let her know about this.

2020-08-19 08:40 UTC, akay08923 commented on library/returnBook/ReturnBookUI.java
> +				String BookInputString = input("Scan book (<enter> completes): ");
a variable name should be bookInputString instead of BookInputString 
@dipanshu42

2020-08-19 08:44 UTC, dipanshu42 commented
Hey ankush
I have let navjeevan know about the change request and she will follow it
up asap

On Wed, 19 Aug, 2020, 6:40 pm akay08923, <notifications@github.com> wrote:

> *@akay08923* requested changes on this pull request.
>
> Hi @dipanshu42 <https://github.com/dipanshu42>, i have reviewed the code
> which has been updated by @navjeevan24 <https://github.com/navjeevan24> .
> there was a one error on which i gave suggestion. Please let her know about
> this.
> ------------------------------
>
> In library/returnBook/ReturnBookUI.java
> <https://github.com/dharam4/jattcode/pull/9#discussion_r472861021>:
>
> >  			
>  			case INITIALISED:
>  				break;
>  				
>  			case READY:
> -				String BoOk_InPuT_StRiNg = iNpUt("Scan Book (<enter> completes): ");
> +				//String BoOk_InPuT_StRiNg = iNpUt("Scan Book (<enter> completes): ");
> +				String BookInputString = input("Scan book (<enter> completes): ");
>
> a variable name should be bookInputString instead of BookInputString
> @dipanshu42 <https://github.com/dipanshu42>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dharam4/jattcode/pull/9#pullrequestreview-470243528>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQK62VPWHXLDNDXPAYM3SEDSBOFXDANCNFSM4QDON3SQ>
> .
>

2020-08-19 09:21 UTC, navjeevan24 commented
hi dipanshu, I done changes in code so can you please informe to ankush for review. 

Sent from my iPhone

> On 19 Aug 2020, at 6:44 pm, dipanshu42 <notifications@github.com> wrote:
> 
> ﻿
> Hey ankush
> I have let navjeevan know about the change request and she will follow it
> up asap
> 
> On Wed, 19 Aug, 2020, 6:40 pm akay08923, <notifications@github.com> wrote:
> 
> > *@akay08923* requested changes on this pull request.
> >
> > Hi @dipanshu42 <https://github.com/dipanshu42>, i have reviewed the code
> > which has been updated by @navjeevan24 <https://github.com/navjeevan24> .
> > there was a one error on which i gave suggestion. Please let her know about
> > this.
> > ------------------------------
> >
> > In library/returnBook/ReturnBookUI.java
> > <https://github.com/dharam4/jattcode/pull/9#discussion_r472861021>:
> >
> > > 
> > case INITIALISED:
> > break;
> > 
> > case READY:
> > - String BoOk_InPuT_StRiNg = iNpUt("Scan Book (<enter> completes): ");
> > + //String BoOk_InPuT_StRiNg = iNpUt("Scan Book (<enter> completes): ");
> > + String BookInputString = input("Scan book (<enter> completes): ");
> >
> > a variable name should be bookInputString instead of BookInputString
> > @dipanshu42 <https://github.com/dipanshu42>
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/dharam4/jattcode/pull/9#pullrequestreview-470243528>,
> > or unsubscribe
> > <https://github.com/notifications/unsubscribe-auth/AQK62VPWHXLDNDXPAYM3SEDSBOFXDANCNFSM4QDON3SQ>
> > .
> >
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-19 09:25 UTC, dipanshu42 commented
Ill let him know

On Wed, 19 Aug, 2020, 7:21 pm navjeevan24, <notifications@github.com> wrote:

> hi dipanshu, I done changes in code so can you please informe to ankush
> for review.
>
> Sent from my iPhone
>
> > On 19 Aug 2020, at 6:44 pm, dipanshu42 <notifications@github.com> wrote:
> >
> > ﻿
> > Hey ankush
> > I have let navjeevan know about the change request and she will follow it
> > up asap
> >
> > On Wed, 19 Aug, 2020, 6:40 pm akay08923, <notifications@github.com>
> wrote:
> >
> > > *@akay08923* requested changes on this pull request.
> > >
> > > Hi @dipanshu42 <https://github.com/dipanshu42>, i have reviewed the
> code
> > > which has been updated by @navjeevan24 <https://github.com/navjeevan24>
> .
> > > there was a one error on which i gave suggestion. Please let her know
> about
> > > this.
> > > ------------------------------
> > >
> > > In library/returnBook/ReturnBookUI.java
> > > <https://github.com/dharam4/jattcode/pull/9#discussion_r472861021>:
> > >
> > > >
> > > case INITIALISED:
> > > break;
> > >
> > > case READY:
> > > - String BoOk_InPuT_StRiNg = iNpUt("Scan Book (<enter> completes): ");
> > > + //String BoOk_InPuT_StRiNg = iNpUt("Scan Book (<enter> completes):
> ");
> > > + String BookInputString = input("Scan book (<enter> completes): ");
> > >
> > > a variable name should be bookInputString instead of BookInputString
> > > @dipanshu42 <https://github.com/dipanshu42>
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub
> > > <
> https://github.com/dharam4/jattcode/pull/9#pullrequestreview-470243528>,
> > > or unsubscribe
> > > <
> https://github.com/notifications/unsubscribe-auth/AQK62VPWHXLDNDXPAYM3SEDSBOFXDANCNFSM4QDON3SQ
> >
> > > .
> > >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dharam4/jattcode/pull/9#issuecomment-676015550>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQK62VN2YZ4ACZ7GAHD4SN3SBOKTHANCNFSM4QDON3SQ>
> .
>

2020-08-19 09:26 UTC, navjeevan24 commented
I changes code again dipanshu please request to ankush for review.

2020-08-19 09:27 UTC, navjeevan24 commented
I changes code again dipanshu please request to ankush for review.

2020-08-19 09:27 UTC, dipanshu42 commented
Already did that

On Wed, 19 Aug, 2020, 7:27 pm navjeevan24, <notifications@github.com> wrote:

> I changes code again dipanshu please request to ankush for review.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dharam4/jattcode/pull/9#issuecomment-676023151>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQK62VN75OUBVZABRKQRTU3SBOLGVANCNFSM4QDON3SQ>
> .
>

2020-08-20 00:12 UTC, navjeevan24 commented
hi dharamveer, Dipanshu again update his code can you please review that and let me know if there any error or not. Thanks

Sent from my iPhone

Begin forwarded message:

> From: dipanshu42 <notifications@github.com>
> Date: 20 August 2020 at 2:00:57 am AEST
> To: dharam4/jattcode <jattcode@noreply.github.com>
> Cc: navjeevan24 <navjeevan444@gmail.com>, Mention <mention@noreply.github.com>
> Subject: [dharam4/jattcode] Payfine dipanshu (#10)
> Reply-To: dharam4/jattcode <reply@reply.github.com>
> 
> ﻿
> Hey @navjeevan24 i have further updated my code can you please ask @dharam4 to review my code and let me know if any changes are required
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/dharam4/jattcode/pull/10
> 
> Commit Summary
> 
> Update PayFineUI.java
> Update PayFineUI.java
> Update PayFineUI.java
> File Changes
> 
> M library/payfine/PayFineUI.java (10)
> Patch Links:
> 
> https://github.com/dharam4/jattcode/pull/10.patch
> https://github.com/dharam4/jattcode/pull/10.diff
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-08-20 06:22 UTC, akay08923 approved these changes
hi @dipanshu42 , Everything is fine. @navjeevan24  can merge the code into master branch.

2020-08-20 09:41 UTC, navjeevan24 commented
ok I will merge it in master branch

2020-08-20 09:43 UTC, navjeevan24 commented
thanks

2020-08-20 13:18 UTC, merged